### ISSUE TITLE
Docker sandboxes - don't allow to extend sandbox on draining instances

### ISSUE THREAD

**Issue by Halama** [keboola/provisioning-bundle#107]
Extend API call should throw user error if sandbox is running on DRAINING instance.

Ref: https://keboola.slack.com/archives/C1BU0N7LZ/p1555325558000200

**Comment by odinuv** [comment]
fixed in https://github.com/keboola/provisioning-bundle/commit/741638ce866bbbc4e434814769dcbe5a3cd71587

pokracovani na UI https://github.com/keboola/kbc-ui/issues/3398
