### ISSUE TITLE
Snowflake - dropped workspace

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/provisioning-bundle#11]
pokud dropnu workspace, začne to házet 500, mělo by to samo nahodit novej workspace (při create) nebo vrátit 404

keboola-provisioning-bundle-d432a14424a39c0b9e6bed92b517336

**Comment by Halama** [comment]
load zacne hazet 500?

**Comment by Halama** [comment]
jo sorry to je provisioning, ja myslel ze hlasis issue do KBC.

**Comment by ondrejhlavacek** [comment]
provisioning vůbec nedělá load, 500 vrátí provisioning, že se nedá přihlásit.
