### ISSUE TITLE
SymfonyTrait used in ECSTrait and DefaultControllerTest

### ISSUE THREAD

**Issue by ujovlado** [keboola/provisioning-bundle#124]
```
PHP Fatal error:  Uncaught Keboola\ProvisioningBundle\Tests\SymfonyTrait and Keboola\ProvisioningBundle\Tests\ECSTrait define the same property ($doctrine) in the composition of Keboola\ProvisioningBundle\Tests\Controller\DefaultControllerTest. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed
```

**Comment by ujovlado** [comment]
Tu je SymfonyTrait:
https://github.com/keboola/provisioning-bundle/blob/741638ce866bbbc4e434814769dcbe5a3cd71587/Tests/ECSTrait.php#L18

To je aj EcsTrait, aj SymfonyTrait:
https://github.com/keboola/provisioning-bundle/blob/741638ce866bbbc4e434814769dcbe5a3cd71587/Tests/Controller/DefaultControllerTest.php#L14-L15

**Comment by odinuv** [comment]
ale je to jen warning, ne?

**Comment by ujovlado** [comment]
Fatal, spadnu mi na tom lokalne testy (ale je divne, ze sa mi to nedeje inde). Vyhodenim SymfonyTrait z DefaultController test sa to fixne.

**Comment by odinuv** [comment]
to je teda divny, ze to dela jen nekde a ze to predtim slo

**Comment by ujovlado** [comment]
`error_reporting = E_ALL`

**Comment by ujovlado** [comment]
V testoch asi budeme mat default alebo nieco menej strictne.

**Comment by ujovlado** [comment]
Poslem failujuci "test"
