### ISSUE TITLE
Upgrade to latest MariaDB

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/provisioning-bundle#15]
Musíme pohnout s upgradem na poslední verzi MariaDB (10.1.18). Aby byl přechod plynulý, budou muset obě verze běžet zároveň. Představuju si to takhle
### 1. Nový backend

Provisioning bude mít nový backend `mariadb-10.1.18`, který podědí vše po `mysql`. Zároveň bude možné pouštět víc backendů naráz.
### 2. AWS Provisioning

Sandbox i Transformační server poběží přes Spot Fleet. Aby se nemusely řešit DNS, bude potřeba v entitě `Servers` udělat to, aby primární klíč nebyl `hostname`. Servery budou nastaveny tak, že budou křížově fallbackovat. Sandbox bude fallback pro transformace a transformace budou fallback pro sandbox (i když tohle by možná stálo za to vůbec nedělat, aby transformační server nezatěžovaly sandboxy).
### 3. UI + TAPI

UI a TAPI budou používat vybranej provisioning podle toho, jakou bude mít **token nebo projekt** featuru nebo nějakej flag runu. Použitá verze se bude logovat. Sandbox stránka bude nabízet souběžně obě verze (aby to nebylo tak zmatený). Nové projekty by defaultně měly bežet na novém, měly by rovnou mít zapnutou featuru (přes šablonu projektu? nebo nějak jinak?). Migrace se potáhne zřejmě několik měsíců a byla by škoda muset migrovat i projekty, které vznikly po začátku migrace.
### 4. Oznámení

Určí se datum, ke kterému starý backend vypneme a napíše se to na status. Datum třeba minimálně 3 měsíce dopředu. Na help.keboola.com by měl bejt podrobnej návod, jak tu migraci otestovat.
#### a) přepínání

Uživatelé budou muset ručně otestovat, jestli je všechno ok. Budou na to tři možnosti 
 1) přepne se globálně celý projekt
 2) přepne se jeden manuální run
 3) přepne se vše puštěné daným uživatelem

Z druhé a třetí bych vybral jednu. 
#### b) klonování

Další varianta je, že by se vytvořil klon projektu, na kterém by se nastavila featura a na ní by se to mohlo v klidu testovat. Pro potřeby testu by tam byly zklonovaný třeba jen data a jen transformace. Po tom, co se to na klonu ověří, bude možno přepnout původní projekt.
### 6. Notifikace

V nějakých intervalech bychom měli kontrolovat stav projektů a notifikovat projekty, který ještě migraci neudělaly. Měsíc před deadline by to mělo v projektu opravdu prudit (na dashboardu?) a dát k tomu link na help.keboola.com.

**Comment by padak** [comment]
@ondrejhlavacek ještě mi tu schází popsaný, proč to děláme. Přijde mi to jako dost práce na to, jak nulově významnej ten mysql backend do budoucna bude. Jaký je s tím issue?

**Comment by ondrejhlavacek** [comment]
@padak dobrej point. děláme to proto, že u mysql 5.5 nedokážeme limitovat délku běhu query, tj. kdokoliv neopatrnej odstřelí sandbox nebo transformační server (stalo se minulý týden) a my můžem jen tiše přihlížet a ad hoc reagovat. 

zbytek cirkusu bude stejně někdy potřeba prošlapat, protože ne všechny migrace/změny jde darklaunchovat.

**Comment by padak** [comment]
ok, ale na sandboxu nám mariadb jede, ne? Takže nestačí říct že od 1.12. bude tapi backend mariadb + dát lidem nějaký magick tlačítko, přes který to v UI spustí na novým backendu, aby si to mohli zkusit? Mířím k tomu, jestli se s tím nedá míň srát. Je tam nějaká super nekompatibilita?

**Comment by ondrejhlavacek** [comment]
Ne, na Sandboxu je MySQL 5.5.44, stejně tak jako na transformačním serveru. Na Sandboxu chvíli byla MariaDB, a měli jsme na Zendesku stížnosti, že to v sandboxu běží jinak než v orchestraci.

**Comment by padak** [comment]
jasně! teď to dává celý smysl! Díky!

**Comment by ondrejhlavacek** [comment]
Nevím co s tím, jsem teď po zkušenostech s Redshiftem bojácnej a skeptickej. Deadline nefungujou, zdánlivě straightforward a otestovaný migrace dojebou živý projekty, a všechno to generuje nespokojený zákazníky :-/. 

To "tlačítko" je popsaný v 5.

**Comment by padak** [comment]
To zvládneme!

**Comment by ujovlado** [comment]
len pre zaujimavost, preco MariaDB 10.1 a nie MySQL 5.7? Kvoli tomu limitu behu query?

**Comment by ondrejhlavacek** [comment]
@ujovlado https://mariadb.org/maria-10-1-mysql-5-7-commodity-hardware/
mysql 5.7+ umí limitovat délku běhu query a mariadb 10.1 je postavená na mysql 5.7 a je rychlejší.

ale argumenty sem! :-) myslím si, že jsme se o mariadb dřív hodně bavili, když jsme ladili výkon, a do tý doby tak nějak bezmyšlenkovitě defaultujem k mariadb. nicméně to, co potřebujem umí i mysql 5.7 a výkon už teď zas tolik neřešíme.

**Comment by Halama** [comment]
MySQL transformace končí koncem měsíce :) http://status.keboola.com/deprecating-mysql-storage-and-transformations
