### ISSUE TITLE
Chybí db migrace

### ISSUE THREAD

**Issue by Halama** [keboola/provisioning-bundle#19]
Nevím jak nahodit strukturu db. U ostatních komponent stačí vytvořit db a pak spustit `php vendor/keboola/syrup/app/console doctrine:migrations:migrate`

**Comment by odinuv** [comment]
ja pouzivam `doctrine:schema:update` a myslim, ze to funguje

**Comment by Halama** [comment]
aha super, tak to zkusim, to jsem zatim nikde nevidel.

**Comment by Halama** [comment]
Tak mi to neslape:
![image](https://cloud.githubusercontent.com/assets/903531/19850799/c34fe70a-9f5a-11e6-8f8b-c20a632dfcd1.png)

U transformaci ale proslo.

**Comment by odinuv** [comment]
to ti dela na mastrovi? to je divny, tam nema enumdockeraccounttype co delat

**Comment by Halama** [comment]
`production` branch

**Comment by ondrejhlavacek** [comment]
je to furt issue?

**Comment by Halama** [comment]
vypada to ze ne. podle tohodle to doctrine schema update slape https://github.com/keboola/syrup-router/blob/master/AWS.md#5-launch-api

zaviram.
