### ISSUE TITLE
Set Timeout for Snowflake Writer Credentials

### ISSUE THREAD

**Issue by MiroCillik** [keboola/provisioning-bundle#23]
Pre credentials `type=writer`, nastavit pri zakladani workspaceu timeout http://docs.keboola.apiary.io/#reference/workspaces/workspaces-collection/create-new-workspace.

Viz https://github.com/keboola/connection/issues/596

**Comment by ondrejhlavacek** [comment]
@MiroCillik ten timeout má bejt zahardcodovanej v provisioningu nebo bude předanej?

**Comment by MiroCillik** [comment]
@ondrejhlavacek myslim, ze to mozes zahardcodovat do provisioningu. Bud to bude hc v provisioningu alebo v UI.

**Comment by ondrejhlavacek** [comment]
A kolik ten timeout ma bejt?

**Comment by MiroCillik** [comment]
Minuta?

**Comment by Halama** [comment]
ja bych to asi ted hardcodnul do provisioningu. Ted by se pak asi casem mel zeptat neceho kolem projektu co ma zaplacene a podle toho to nastavit.

**Comment by Halama** [comment]
takze to nebude parametr provisioningu

**Comment by ondrejhlavacek** [comment]
fixed by 988fb2999f8567b6232d4483a1ec39a4ac1ca085
