### ISSUE TITLE
Docker async job

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/provisioning-bundle#25]
neuloží do resultu jméno/heslo, ale jen id credentials, GET na api pak vrátí i jméno a heslo

**Comment by odinuv** [comment]
no myslim, ze jsem to udelal proto, aby nemuselo UI resit dalsi API call. Oboji je pristupny stejnym tokenem.

**Comment by ondrejhlavacek** [comment]
Ten job je vidět vsema tokenama projektu

**Comment by odinuv** [comment]
nj, neuvedomil jsem si, ze provisioning kontroluje tokeind

**Comment by ondrejhlavacek** [comment]
Fixed by ca5998d
