### ISSUE TITLE
Docker Sandboxes on a different stack

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/provisioning-bundle#51]
Dataloader does not seem to be able to load data

https://keboola.slack.com/archives/C1BU0N7LZ/p1498710468075346

**Comment by ondrejhlavacek** [comment]
[object] (Keboola\StorageApi\ClientException(code: 401): Invalid access token at /appcode/vendor/keboola/storage-api-client/src/Keboola/StorageApi/Client.php:1903, GuzzleHttp\Exception\ClientException(code: 401): Client error: `POST https://connection.keboola.com/v2/storage/tickets` resulted in a `401 Unauthorized` response:
{"error":"Invalid access token","exceptionId":"keboola-connection-73b86e45d8fe558b652dea6e3d027890","code":"storage.toke
 at /appcode/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111

**Comment by Halama** [comment]
tohle už je fixnutý
