### ISSUE TITLE
docker sandboxes https

### ISSUE THREAD

**Issue by Halama** [keboola/provisioning-bundle#54]
Docker sandboxy zatím nepodporují https, přístup k sandboxu je teď přímo public DNS ec2 instance a číslo portu pod kterým běží konkrétní sandbox např. http://ec2-52-206-76-45.compute-1.amazonaws.com:9641/

Napadají mě zatím dvě možnosti jak přidat podporu https.

## HTTPS terminováno přímo kontejnerem
V tomhle případě to bude fungovat v podstatě stejně jako doposud, url sandboxu který vrátí provisioning bude vypada např. https://i-0e3860db2bbe86f4f-sandbox.us-east-1.keboola.com:9641 a https://i-0e3860db2bbe86f4f-sandbox.eu-central-1.keboola.com:9641

### Implementace

- [x] Na hostitelské instance clusteru budou staženy (nově koupené) certifikáty z S3, zařídí se během provisioningu instance
- [x] EC2 Instance se musí v moment provisioningu zaregistrovat do DNS Route 53 např. jako `INSTANCE_ID`.sandboxes.keboola.com - mělo by být parametrizováno v CF template. Registrovaný hostname se zároven nastaví jako tag např. `KeboolaDNS` instance pro další použití.
- [x] ECS task definition sandboxu bude obsahovat nový kontejner ve kterém bude (ngingx, apache, ..) proxy která bude terminovat https (certifikáty nalinkovány přes mount z hostu) a bude napojena interně na kontejner ze sandboxem https://github.com/keboola/provisioning-bundle/blob/79610aa5d24f5e4b1534129cf604326a106c6a26/Entity/Server/Docker.php#L225 TODO: ověřit řešení lokálně
- [x] Provisioning v moment vytvoření sandboxu musí vracet Keboola hostname místo public DNS ec2 instance. Keboola hostname by mělo být možné získat z tagu `KeboolaHostname` instance. https://github.com/keboola/provisioning-bundle/blob/79610aa5d24f5e4b1534129cf604326a106c6a26/Entity/Server/Docker.php#L513

## HTTPS terminované load balancerem
V tomhle případě by URL sandboxu vypadalo např. https://rstu-236-3810.sanboxes-01.keboola.com

Pro docker sandboxy je připraven jeden nebo více ALB s https listenery. Pro každý sanbox by bylo zaregistrování `host` pravidlo a `Target group` ve které by byl jako target vždy jeden kontejner konkrétního sandboxu.

### Vytvoření ALB
Load balancer se  musí zaregistrovat do provisioningu aby do něj poté mohl registrovat services/tasky.
V rámci provisioningu ALB by se mělo zároven nastavit jeho wildcard DNS např. `*.sandboxes-01.keboola.com`

### Vytvoření sandboxu
- Vytvoření ALB Target Group
- Přidání pravidla do listeneru ALB a namapování host na vytvořenou Target Group http://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-update-rules.html - ALB se vybere z tech které jsou zaregistrované v provisioningu
- Nahození ECS service která spustí připravený Task definition sandbox a  `sandbox` kontejner propojí s připravenou Target Group http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html#ECS-CreateService-request-loadBalancers

### Limity!!

- `Rules per load balancer (not counting default rules): 100` - Nejde měnit, proto bude potřeba podpora více ALB
- `Target groups per region: 200` - Jde zvednout, otázka je na kolik. 1 target group se rovná jeden sandbox!
- `Load balancers per region: 20` - Jde zvednout

**Comment by Halama** [comment]
první variantu ssl proxy testuju tady https://github.com/keboola/docker-rstudio/pull/2

**Comment by Halama** [comment]
Jinak bych asi byl pro druhou variantu ale ta je přeci jen pracnější a  některé kroky jako switch na ASG a práci s Route 53 je potřeba vyřešit i v první variantě takže bych asi žačal tou pokud se neobjeví nějaký blocker.

**Comment by Halama** [comment]
Tady připravuju image pro proxy kontejner https://github.com/keboola/docker-sandbox-ssl-proxy
Měl by být univerzální pro Jupyter i rstudio, jenom je tam potřeba trochu hacknout v proxy_pass PORT kontejneru. https://github.com/keboola/docker-sandbox-ssl-proxy/blob/5df2bcb9ce4a42190a28701a0bd730f82ff03294/run.sh#L3

**Comment by Halama** [comment]
Proxy je hotová a pushnutá do ECR https://github.com/keboola/docker-sandbox-ssl-proxy
Teď už bude možné to vyzkoušet v ECS s ručně naklikanými Task definitions atd.

**Comment by Halama** [comment]
## Ověření první verze
- [ ] Dotáhout autoscaling template tak at nahodí SB instanci a stáhne na ní certifikáty (z jednoho S3 bucketu - bude přístupný i pro devel)
- [ ] Ručně připravit task definition s loader, sandbox a proxy kontejnerem.
- [ ] Ručně na instanci nasměrovat DNS
- [ ] Ověřit funkčnost jupyter sandboxu
- [ ] Ověřit funkčnost R studio sandboxu

**Comment by Halama** [comment]
Nahozený testovací stack s upravenou ASG s certifikáty a ručně vytvořeným Jupyter task definition.
Spuštění tasku:
```
aws ecs run-task \
 --cluster martin-docker-sandbox-dev \
 --task-definition martin-https-sandbox:4 \
 --count 1 \
 --overrides file://overrides.json
```
overrides.json
```json
{
 "containerOverrides": [
   {
     "name": "data-loader",
     "environment": [
       {
         "name": "KBC_EXPORT_CONFIG",
         "value": "{\"storage\":{\"input\":{\"tables\":[{\"source\":\"in.c-100.testuj\",\"destination\":\"in.c-100.testuj.csv\"}]}}}"
       },
       {
         "name": "KBC_STORAGEAPI_URL",
         "value": "https://connection.keboola.com"
       },
       {
         "name": "KBC_TOKEN",
         "value": "TOKEN"
       }
     ]
   },
   {
     "name": "sandbox",
     "environment": [
       {
         "name": "USER",
         "value": "martin"
       },
       {
         "name": "PASSWORD",
         "value": "p]cgx6b8WXUXp7WWjEV"
       }
     ]
   }
 ]
}
```


Poznámka - proč se v produkci každému zakládá vlastní Task Definiton když se vše stejně přetěžuje ENV proměnnými při spuštění?

**Comment by Halama** [comment]
Nastavil jsem ručně DNS na instanci a Jupyter valí!
https://jupy-236-3810-sandbox.keboola.com:32771

**Comment by Halama** [comment]
Kompletní Task Definition pro Jupyter:
```json
{
  "containerDefinitions": [
    {
      "memory": 128,
      "mountPoints": [
        {
          "containerPath": "/data/",
          "sourceVolume": "data",
          "readOnly": false
        }
      ],
      "name": "data-loader",
      "image": "147946154733.dkr.ecr.us-east-1.amazonaws.com/keboola/data-loader:latest"
    },
    {
      "volumesFrom": [
        {
          "readOnly": null,
          "sourceContainer": "data-loader"
        }
      ],
      "memory": 128,
      "links": [
        "data-loader"
      ],
      "image": "147946154733.dkr.ecr.us-east-1.amazonaws.com/keboola/docker-jupyter:latest"
    },
    {
      "memory": 128,
      "portMappings": [
        {
          "hostPort": 0,
          "containerPort": 443,
          "protocol": "tcp"
        }
      ],
      "mountPoints": [
        {
          "containerPath": "/etc/ssl/certs/nginx/proxy.crt",
          "sourceVolume": "certificate-crt",
          "readOnly": null
        },
        {
          "containerPath": "/etc/ssl/certs/nginx/proxy.key",
          "sourceVolume": "certificate-key",
          "readOnly": null
        }
      ],
      "name": "proxy",
      "environment": [
        {
          "name": "KEBOOLA_SANDBOX_PORT",
          "value": "8888"
        }
      ],
      "links": [
        "sandbox"
      ],
      "image": "147946154733.dkr.ecr.us-east-1.amazonaws.com/keboola/docker-sandbox-ssl-proxy:latest"
    }
  ],
  "volumes": [
    {
      "host": {
        "sourcePath": null
      },
      "name": "data"
    },
    {
      "host": {
        "sourcePath": "/home/ec2-user/certificates/x.keboola.com.crt"
      },
      "name": "certificate-crt"
    },
    {
      "host": {
        "sourcePath": "/home/ec2-user/certificates/x.keboola.com.key"
      },
      "name": "certificate-key"
    }
  ]
}
```

**Comment by Halama** [comment]
A Rstudio valí taky!
https://i-0584a4a1fb298ac36-sandbox.keboola.com:32772/

Rozdíl v Task Definition je pouze použitý image pro sandbox a nastavení env proměnné `KEBOOLA_SANDBOX_PORT` proxy kontejneru.

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/28408578-42218ae2-6d38-11e7-9ba6-bff69e7f6fff.png)

**Comment by Halama** [comment]
Založení DNS pro instanci by možná mohlo jít řešit pomocí tohodle https://github.com/awslabs/aws-lambda-ddns-function

**Comment by Halama** [comment]
^ přijde mi asi zbytečně komplikované (i když tam na to mají CF template), zkusím ten záznam spíš založit z CF provisioningu jako to teď tagujeme.

**Comment by Halama** [comment]
Pokračuju na nahození DNS instance https://github.com/keboola/syrup-router/pull/57/commits/afe19f1d24316a7ccfea2b7e56d253ae6eaa8752

**Comment by Halama** [comment]
DNS a vše co se týče provisioningu instance je hotové.

**Comment by Halama** [comment]
### Shrnutí
Je připraven provisioning varianty kdy je https terminováno přímo kontejnerem. Tzn. bude to fungovat v podstatě stejně jako doposud, URL sandboxů budou např. https://i-0e3860db2bbe86f4f-sandbox.us-east-1.keboola.com:9641 a https://i-0e3860db2bbe86f4f-sandbox.eu-central-1.keboola.com:9641

Můj dev stack na kterém se na to dá mrknout v provozu je tady https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn:aws:cloudformation:us-east-1:061240556736:stack%2Fmartin-docker-sandbox-dev%2Ffa437d70-6d14-11e7-8b13-50d5caf92cd2

A sandboxy s nastaveným hostname:
- https://i-0584a4a1fb298ac36-sandbox.keboola.com:32772/
- https://i-0584a4a1fb298ac36-sandbox.keboola.com:32771/

### Další kroky
- [ ] Koupit certifikáty `*.eu-central-1.keboola.com`, `*.us-east-1.keboola.com`
- [ ] Nahodit do produkce nové stacky podle https://github.com/keboola/syrup-router/pull/57 Aktuální provisioning bez https by na nich měl jet v pohodě a zároveň to bude ready na nový https provisioning
- [ ] Upravit provisioning https://github.com/keboola/provisioning-bundle tak aby
  - [ ] Nahazoval sandboxy s novým task definition obsahující proxy kontejner https://github.com/keboola/provisioning-bundle/issues/54#issuecomment-316633064
  - [ ] v moment vytvoření sandboxu musí vracet Keboola hostname místo public DNS ec2 instance. Keboola hostname se získá z tagu instance `KeboolaDNS`. 
https://github.com/keboola/provisioning-bundle/blob/79610aa5d24f5e4b1534129cf604326a106c6a26/Entity/Server/Docker.php#L513
  - [ ] Vyhodit z provisioningu generování portu, stačí nastavit na `0` a jako je to v nalinkované task definition a ECS se o vybrání portu postará samo https://github.com/keboola/provisioning-bundle/blob/79610aa5d24f5e4b1534129cf604326a106c6a26/Entity/Server/Docker.php#L448 
  - [ ] Začít v UI linkovat sandbox pod https. Jak se pozná že už podporuje https? Možná bude dobré do odpovědi provisioningu přidat nějaký flag 
![image](https://user-images.githubusercontent.com/903531/28454525-e383a168-6dfb-11e7-8aa6-07c04baf83bf.png)

**Comment by odinuv** [comment]
[ ] - port se musi vytahnout z beziho tasku `proxy` z network bindings http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeTasks.html
[ ] - UI bude potreba upravit teda jeste pred provisioningem (predpokladam, ze jak zapnem HTTPS tak prestane fungovat HTTP)

**Comment by Halama** [comment]
Ten přechod jsem si představoval takhle: 
- nahodí se nový cluster s certifikáty a DNS a zaregistruje se do provisioningu.
- Provisioning na novém cluster začne spouštět stávající http sandboxy s AWS dns
- Deployne se úprava provisioningu kdy začne vracet `isHttps` flag
- Deployne se úprava ui rozlišující https pro link
- Deployne se úprava provisioningu kdy začne nahazovat https sandboxy.

**Comment by Halama** [comment]
Ještě nevím jak urychlit vypnutí tech starých běžících sandboxů, vím že expirují ale někdo si ho může do nekonečna protahovat :)

**Comment by odinuv** [comment]
no tak to se pak muzem podivat za tyden na cluster co tam zustalo a napsat jim

**Comment by Halama** [comment]
ten můj testovací stack jsem zatím smáznu at to nepálí $

**Comment by Halama** [comment]
Nahozen a zaregistrován nový stack do EU. Stávající http sandboxy na něm jedou v pohodě.
Ručně jsem nahodil https sandbox a taky jede https://i-067d42d870c5c42b1-sandbox.eu-central-1.keboola.com:32768/

**Comment by Halama** [comment]
Nový stack nahozen a aktivován v US, starý deaktivován a zatím ho nechám doběhnout až tam expirují běžící sandboxy.
Test ručně nahozeného https sandboxu https://i-0d1fac55af7808d20-sandbox.us-east-1.keboola.com:32769/

Ted už zbývá upravit ui a provisioning a je to.

**Comment by Halama** [comment]
První PR kdy jenom přidávám flag do db https://github.com/keboola/provisioning-bundle/pull/57
V druhém bych ho začal načítat z db.
A ve třetím implementoval https sandboxy.

**Comment by Halama** [comment]
První dva PR jsou nasazený.
A podpora https je ready tady https://github.com/keboola/provisioning-bundle/pull/61
Teď na to https připravím UI ať podporuje obě varianty. 
Dál bude potřeba upravit klient ať umí pracovat s https.

**Comment by Halama** [comment]
podpora v UI je připravená tady https://github.com/keboola/kbc-ui/pull/1077 a jdu ji mergnout, podporuje obě varianty.

**Comment by Halama** [comment]
PR na klienta https://github.com/keboola/provisioning-client/pull/10

**Comment by Halama** [comment]
asi to zkusím pomergovat

**Comment by Halama** [comment]
mergnul jsem a nasadil. A při hraní z jupyterem jsem zjistl že používá web sockety a nejedou tak revert a debug.

**Comment by odinuv** [comment]
a fakt nefunguje nebo to jen nekam pise? nejakou hlasku o nespojenym websocektu uz jsem tam videl, ale nic to nedelalo

**Comment by Halama** [comment]
Vyzkoušej: https://i-0d1fac55af7808d20-sandbox.us-east-1.keboola.com:32772/notebooks/notebook.ipynb

**Comment by Halama** [comment]
asi to ale pujde https://aptro.github.io/server/architecture/2016/06/21/Jupyter-Notebook-Nginx-Setup.html zkustím to podle tohodle

**Comment by Halama** [comment]
Websockets a jupyter vyreseno tady https://github.com/keboola/docker-sandbox-ssl-proxy/pull/1
Pokud budeme casem uvazovat o AWS ELB je tam potreba to chovani socketu overit.

Je to nasazene do produkce.

**Comment by Halama** [comment]
Mělo by to být hotové a zavírám. Ještě bude potřeba připravit status a updatnout dokumentaci.
