### ISSUE TITLE
Remove non-workspace redshift support

### ISSUE THREAD

**Issue by Halama** [keboola/provisioning-bundle#56]
Ted jsem se nad tím zapotil při nahazování testů. Přitom už se to v produkci nepoužívá.

https://keboola.slack.com/archives/C1BU0N7LZ/p1501156670697125

**Comment by Halama** [comment]
hmm, tak možná se to ještě používá na writery?

**Comment by Halama** [comment]
Normální RS writer ale nabízí workspace:
![image](https://user-images.githubusercontent.com/903531/28670304-597670e0-72d8-11e7-8bf1-7783e28a5fa5.png)

**Comment by Halama** [comment]
Ale qlik vrací tohle starý:
https://www.dropbox.com/s/3tlv24yxbnbpl49/Screenshot%202017-07-27%2014.32.34.png?dl=0

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/28670356-92b9fe4e-72d8-11e7-96b2-a14afc733f06.png)

**Comment by Halama** [comment]
@kacurez to debugnul. Udělá fix v ui a už i qlik a looker budou nabízet `redshift-workspace`.

**Comment by odinuv** [comment]
qlik a looker je teda prehozeny https://keboola.slack.com/archives/C02KU1V9S/p1501589817715438?thread_ts=1501499016.040684&cid=C02KU1V9S tak uz jen zjistit jestli existuji nejake stare aktivni konfigurace

**Comment by ondrejhlavacek** [comment]
Good News 1: od  2017-09-19 06:40:25 nevznikl žádnej novej redshift account

**Comment by ondrejhlavacek** [comment]
```sql
SELECT `type`, COUNT(*) FROM `RedshiftAccount` WHERE active = 1 GROUP BY `type`;
```

![image](https://user-images.githubusercontent.com/497675/36280580-04b71bb4-129b-11e8-9ff7-f82556c7c28e.png)

`luckyguess` můžeme vyházet rovnou, jdu pustit GC

**Comment by ondrejhlavacek** [comment]
```sql
SELECT hostname, count(*) FROM `RedshiftAccount` 
WHERE active = 1 AND `type` IN ("read", "write") 
GROUP BY hostname
```

![image](https://user-images.githubusercontent.com/497675/36280785-c1e05ca0-129b-11e8-9a3a-d3f7329adc33.png)

jdu projít neexistující clustery a projekty a ty taky vyházet

**Comment by ondrejhlavacek** [comment]
pročištěno, zbylo 11 projektů

```sql
SELECT tokenOwnerId, count(*) FROM `RedshiftAccount` 
WHERE active = 1
GROUP BY tokenOwnerId
```

![image](https://user-images.githubusercontent.com/497675/36281310-89d1d346-129d-11e8-8e28-a8a38e714616.png)

**Comment by ondrejhlavacek** [comment]
Napsal jsem na slack všem regionům, kterých se to týká.

**Comment by ondrejhlavacek** [comment]
![image](https://user-images.githubusercontent.com/497675/43400848-116f51be-940f-11e8-94ff-a2c4db3bb4f0.png)

v podstatě se nic nezměnilo

**Comment by ondrejhlavacek** [comment]
Zkusím se na to ještě podívat přes konfigurace

**Comment by ondrejhlavacek** [comment]
https://connection.keboola.com/admin/projects/258/transformations/bucket/423725199/transformation/423725203

**Comment by ondrejhlavacek** [comment]
CA: all clear

**Comment by Halama** [comment]
jenze ten token tam chybi, tak teda nevim co s tim.

**Comment by ErikZigo** [comment]
@ondrejhlavacek ping

**Comment by ondrejhlavacek** [comment]
sorry, byl jsem tu zahrabanej a ještě trochu budu, tomuhle dávám lowprio. na ticket mu odpovím a teď s tím nic dalšího dělat nebudu, až budou vyřešený všechny projekty, smažu to ručně z db.

**Comment by ondrejhlavacek** [comment]
> otevírám jeden starší ležák, v projektu *** (1046) eviduju ještě jednu konfiguraci, kde jsou použitý legacy Redshift credentials (ty maj prefix static_).

Ahoj,
melo by to byt vyreseno. Promin, ze to trvalo, je toho ted hodne.
V.

https://keboola.zendesk.com/agent/tickets/8884
