### ISSUE TITLE
Jupyter Sandbox: load packages

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/provisioning-bundle#64]
packages specified in a transformation are not loaded

**Comment by Halama** [comment]
Není to jenom tím že ty packages neposílá ui?

**Comment by Halama** [comment]
https://github.com/keboola/provisioning-bundle/blob/acf74fb56fd34ebc99be291b7ff71a3f6a2c196b/Controller/AsyncController.php#L80

**Comment by Halama** [comment]
asi to chybí jenom v dokumentaci

**Comment by Halama** [comment]
UI už to tam posílá ale ještě to asi není uplně ok:
 - Při neexistujícím package to nefailne
 - U tagů říká že nejsou array, taky by mělo failnout 

```
Aug 28 15:33:28 kbc-us-east-1-docker-sandbox-i-0d1fac55af7808d20 ecs-jupy_236_3810-23-sandbox-baaeb0a980aec7c87e00:  Collecting hovno
Aug 28 15:33:28 kbc-us-east-1-docker-sandbox-i-0d1fac55af7808d20 ecs-jupy_236_3810-23-sandbox-baaeb0a980aec7c87e00:  Initializing Jupyter
Aug 28 15:33:28 kbc-us-east-1-docker-sandbox-i-0d1fac55af7808d20 ecs-jupy_236_3810-23-sandbox-baaeb0a980aec7c87e00:  Loading script into notebook
Aug 28 15:33:28 kbc-us-east-1-docker-sandbox-i-0d1fac55af7808d20 ecs-jupy_236_3810-23-sandbox-baaeb0a980aec7c87e00:  Loading packages "["hovno"]"
Aug 28 15:33:28 kbc-us-east-1-docker-sandbox-i-0d1fac55af7808d20 ecs-jupy_236_3810-23-sandbox-baaeb0a980aec7c87e00:    Could not find a version that satisfies the requirement hovno (from versions: )
Aug 28 15:33:28 kbc-us-east-1-docker-sandbox-i-0d1fac55af7808d20 ecs-jupy_236_3810-23-sandbox-baaeb0a980aec7c87e00:  No matching distribution found for hovno
Aug 28 15:33:28 kbc-us-east-1-docker-sandbox-i-0d1fac55af7808d20 ecs-jupy_236_3810-23-sandbox-baaeb0a980aec7c87e00:  Tags is not JSON array.
Aug 28 15:33:28 kbc-us-east-1-docker-sandbox-i-0d1fac55af7808d20 ecs-jupy_236_3810-23-sandbox-baaeb0a980aec7c87e00:  Loading tagged files from "["vpc"]"
Aug 28 15:33:28 kbc-us-east-1-docker-sandbox-i-0d1fac55af7808d20 ecs-jupy_236_3810-23-sandbox-baaeb0a980aec7c87e00:  Tags is not JSON array.
```

**Comment by kacurez** [comment]
imho pod tie vypisy do stderr staci pridat `sys.exit(1)`

**Comment by Halama** [comment]
podle me je to celý nějaký nefunkční, @odinuv můžeš to prosím otestovat

**Comment by Halama** [comment]
Ty tagy je asi ještě potřeba přidat do `input.files` ?

**Comment by odinuv** [comment]
jo tagy tam musi byt jakoby dvakrat, podivam se na to proc to nefailuje

**Comment by Halama** [comment]
Takže pro tags: `["hovno","neco"]` by IM měl vypadat?:
```
{
    "storage": {
        "input": {
            "files": [
                {
                    "tags": ["hovno"]
                },
                {
                    "tags": ["neco"]
                }
            ]
        }
    }
}
```

**Comment by odinuv** [comment]
cela konfigurace ma vypadat takhle
```
{
  "type": "jupyter",
  "script": "some script code",
  "tags": ["pokus"],
  "packages": ["ccxt"],
  "input": {
    "files": [ 
      {
        "tags": ["pokus"]
      }
    ]
  }
}
```

ty tags jsou tam dvakrat, protoze node `input.files.tags` naloaduje data ze storage do `data/in/files` a node `tags` z nich vybere posledni a naloaduje ho do `/data/in/user`.  V konfiugraci, kterou generuje tedka UI chybi ta prvni node, takze se nenaloduje nic (druhy bez prvniho nedava smysl, prvni bez druhyho jo). Hlaska `Tags is not JSON array.` odpovida tomu, ze to tam neni, fatalni chyba to byt nema protoze je to nepovinne. Rekl bych, ze to funguje jak ma, jen to neni nikde popsany

**Comment by Halama** [comment]
jo pro ty tagy je to takhle ok. Ale pro ty packages by to na neexistujim melo failnout ne? Alespon transformace failne ale sandbox ne, testoval jsem teda jupyter.
A tady by to asi melo rict packages misto tags https://github.com/keboola/docker-jupyter/blob/63369aabc33fa4d797a8a51d345d3815151fbf54/jupyter_notebook_config.py#L80

**Comment by odinuv** [comment]
aha na neexistujicim, jo tak to se podivam, typo fixed

**Comment by kacurez** [comment]
ok tak ja do ui doplnim ten prvy node tj `input.files.tags` pre generovanie IM s tagmi

**Comment by ondrejhlavacek** [comment]
## python chybějící package

![image](https://user-images.githubusercontent.com/497675/29843649-7b40b930-8cc1-11e7-8c5b-d020da5102a4.png)

job transformací končí chybou

![image](https://user-images.githubusercontent.com/497675/29843680-94be5e08-8cc1-11e7-85c7-ece5ae0770f0.png)

job sandboxu proběhne

## python chybějící tags

![image](https://user-images.githubusercontent.com/497675/29843649-7b40b930-8cc1-11e7-8c5b-d020da5102a4.png)

job transformace končí chybou

![image](https://user-images.githubusercontent.com/497675/29843731-c8f95b00-8cc1-11e7-9576-95d9603a2f4b.png)

job sandboxu proběhne

**Comment by ondrejhlavacek** [comment]
Tu samou várku testů jsem nahodil i na RStudio a když chybí package nebo tag, tak ten sandbox nedojede (po 5 minutách jsem to utnul).

**Comment by odinuv** [comment]
no zbezne jsem na to koukl a to bezi nejak v jinym vlakne, podivam se poradne zitra

**Comment by odinuv** [comment]
tak Rstudio je fixnuty

**Comment by odinuv** [comment]
ma to teda vadu v tom, ze to skonci aplikacnim errorem, ale to je ted neresitelny - nema se o z tama jak dostat do eventu. Asi by bylo do toho UI v pripade chyby dobry napsat nejakou vetu jako "verify that packages are correct"

**Comment by odinuv** [comment]
jupyter taky fixnutej

**Comment by odinuv** [comment]
fixed in 7c86ed34c87761fa1ca55d82984d1e6dddc7dc40
