### ISSUE TITLE
Docker sandboxes - Container Overrides length must be at most 8192

### ISSUE THREAD

**Issue by Halama** [keboola/provisioning-bundle#66]
SAPI mapping a skripty bude potřeba posílat nějak jinak než přes ENV proměnné v container overrides run task.
https://connection.keboola.com/admin/utils/logs?file=2017/09/06/15/2017-09-06-15-05-34-59aff29ee0d88-exception

https://connection.keboola.com/admin/utils/logs?file=2017/09/06/15/2017-09-06-15-05-35-59aff29f043cd-log

**Comment by Halama** [comment]
předat data loderu jen token a id konfigurace?

**Comment by odinuv** [comment]
jeste se tam bude muset poslat aktualni verze

**Comment by Halama** [comment]
Ono se to ted koukám posílá inline všechno v parametrech jobu, takže to bude potřeba upravit tak aby se tomu dalo id a verze konfigurace?
![image](https://user-images.githubusercontent.com/903531/30116033-b276bff6-931c-11e7-8594-c16a4e20b17b.png)

**Comment by Halama** [comment]
tvl, ono to v resultu vrací něco!

**Comment by odinuv** [comment]
jo, pokud se tomu preda id konfigurace, tak se to nebude muset posilat online, vraci to id vytvorenych credentials

**Comment by odinuv** [comment]
Takze videl bych to asi na:
- [ ] upravit data-loader aby prijimal id konfigurace a verzi, komponentu bude mit hardcoded `transformations`
- [ ] data loader stahne z konfigurace `script` a `storage`, storage zpracuje soucasnym zpusobem, script ulozi do `/data/` (bude se muset rozhodnout jestli R/Python, nebo to nechat az na sandbox?)
- [ ] upravit R a Jupyter sandbox aby skirpt nenacitaly z envu, ale ze souboru
- [ ] upravit provisioning aby prijimal a DL posilal id a verzi konfigurace
- [ ] upravit UI, aby posilalo novy parametry API callu
- [ ] odstranit stare parametry API callu z provisioningu
- [ ] odstranit stare parametry z data-loaderu
- [ ] odstranit stare parametry z R / Jupyter sandboxu

**Comment by ondrejhlavacek** [comment]
Co kdyby to script uložilo do `/data/in/scripts` nebo tak něco? Dávalo by to smysl?

**Comment by odinuv** [comment]
nedavalo, v transformacich se s tim nepracuje a v sandboxu je potreba dodrzet current directory `/data/` takze to bude muset nejspis byt tam

**Comment by ondrejhlavacek** [comment]
Ticket na Zendesku uzavírám, fix necháme probublat přes weekly status.

**Comment by odinuv** [comment]
dodelano v  7c86ed34c87761fa1ca55d82984d1e6dddc7dc40, stary API call i podpora v data-loader i v sadnboxech zustava kvuli plain sandboxum, cili na transformace je novy api call http://docs.provisioningapi.apiary.io/#reference/credentials-async-actions/transformation-sandbox-credentials-async/create-credentials
