### ISSUE TITLE
new/reused tasks on draining instance

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/provisioning-bundle#72]
přepnu v ECS instanci do DRAINING, ale tasky se na ní furt spouští (pouze ty, co tam v tu chvíli běžely)

funguje to tak, že když task terminuju a založím ho znovu, pustí se znovu na té stejné (i když draining) instanci

https://keboola.slack.com/archives/C02CGRFGU/p1518443657000038

**Comment by ondrejhlavacek** [comment]
https://papertrailapp.com/groups/23635/events?q=rstu_976_73089&focus=898026979692003339

**Comment by Halama** [comment]
tahle instance je aktivni i-0b733c8bc51b0ab6f-sandbox takze je to ok

**Comment by ondrejhlavacek** [comment]
aha, tak ono to běží na obou instancích

![image](https://user-images.githubusercontent.com/497675/36100468-a9e9b41c-1006-11e8-9021-86cf47f50fa0.png)

**Comment by Halama** [comment]
jo to je ono, neco takoveho jsem tusil. Jeden tam stara revize

**Comment by ondrejhlavacek** [comment]
zkusím ještě prohledat ty ostatní sandboxy, nemá to takhle každej

**Comment by odinuv** [comment]
nj obcas se to stane, ze se vytvori dve revize https://github.com/keboola/provisioning-bundle/issues/65 ale nevim presne proc, nepodarilo se me to nasimulovat

**Comment by ondrejhlavacek** [comment]
tak, chtěl jsem to všechno ručně zkontrolovat a zjistit, kdy ty sandbxy byly naposled prodloužený (nebo kdy vytvořený) a kdyžtak je ukončit ručně, ale extendování sandboxu nezakládá event. takže nejdřív doplnit event a pak se to může ručně prozkoumat.

**Comment by odinuv** [comment]
tak uz to loguje extendovani

**Comment by ondrejhlavacek** [comment]
pecka dík, po dovče na to zase mrknu :-)

**Comment by Halama** [comment]
Chci v EU vypnout jednu starou instanci tak zkouším zjistit jestli skutečně ty SB co tam běží existují.

**Comment by Halama** [comment]
Nasetupoval jsem sběř v Sharec configu i z EU a nasypal to do transformace https://connection.keboola.com/admin/projects/258/transformations/bucket/381438271/transformation/381438279

Pro sandbox `rstu_125_777` který běží od ` 2018-04-07 14:36:28 +0200` jsem nenašel active záznam. 
Pro další sandbox `rstu_120_764` který vzniknul `2018-04-07 14:00:43 +0200` jsem taky nenašel žádný active záznam.

**Comment by Halama** [comment]
ARN vůbec nejsou v záznamech např. `ea433563-7dbc-49ed-94fc-9f893a24ad7e`
Hádám že vznikli díky #78

**Comment by Halama** [comment]
Jdu je zabít

**Comment by Halama** [comment]
V EU pročištěno a staženo na jednu čerstvou instanci. Ještě mrknu na US.

**Comment by Halama** [comment]
Tohle bych zavřel, pokračujš v #78
