### ISSUE TITLE
Jupyter: Request entity too large

### ISSUE THREAD

**Issue by odinuv** [keboola/provisioning-bundle#84]
Jupyter uklada prubezne notebook pomoci PUT requestu na svoje API, pokud velikost notebooku prekroci ~1M, tak to hodi 

```
2018/07/19 10:50:29 [error] 10#10: *221 client intended to send too large body: 1204417 bytes, client: 178.22.116.252, server: rstudio, request: "PUT /api/contents/notebook.ipynb HTTP/1.1", host: "i-06890dd443976103a-sandbox.us-east-1.keboola.com:33887", referrer: "https://i-06890dd443976103a-sandbox.us-east-1.keboola.com:33887/notebooks/notebook.ipynb"
```

https://papertrailapp.com/groups/23635/events?focus=956553838041632813&selected=956553838041632813

nasimulovat se to da tak, ze si clovek vytvorit python sandbox a vlozi do notebooku ~1MB textu, pak to zacne sypat do logu tuhle hlasku a prestane to notebook ukladat, lokalne mi to nedela, takze predpokladam, ze to je neco v aws infra, co to limituje?

**Comment by Halama** [comment]
Imho to věc AWS nebude, není tam ani ELB. Mohlo by to být tou proxy ale.

**Comment by Halama** [comment]
zkouším to, dám vědět.

**Comment by Halama** [comment]
bude to imho tohle http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by Halama** [comment]
https://github.com/keboola/docker-sandbox-ssl-proxy
