### ISSUE TITLE
Workspace id - store as bigint/varchar

### ISSUE THREAD

**Issue by Halama** [keboola/provisioning-bundle#97]
Related to https://github.com/keboola/connection/issues/1628#issuecomment-466788388

Možná by se rovnou mohlo ukládat jako VARCHAR viz. https://github.com/keboola/connection/issues/1734 ? API to pořád ale vrací jako číslo.

https://github.com/keboola/provisioning-bundle/blob/34f7fdc3029744b5057f8ad23bf39c2afe91937b/Entity/Account/Workspace.php#L18

**Comment by ondrejhlavacek** [comment]
Odpoledne na to mrknu, ale myslím, že by ten varchar mohl projít.

**Comment by ondrejhlavacek** [comment]
V kódu bude potřeba změnit typehinty u tapi, provisioning clienta a provisioningu, ale nic velkýho.

**Comment by Halama** [comment]
Bacha na to že sapi to pořád vrací jako číslo v API response.

**Comment by ondrejhlavacek** [comment]
![image](https://user-images.githubusercontent.com/497675/53356434-b421c600-392b-11e9-9dcc-aaa73f6ce7d2.png)

![image](https://user-images.githubusercontent.com/497675/53356464-c4d23c00-392b-11e9-90f9-8f9c52ba2b92.png)

Tak nevím, minuta je docela na hranici, co myslíš @Halama? Tolik trafficu tam zase nebejvá... Čistý by bylo začít používat novej sloupeček, zapisovat do obou a po čase ten starej vyhodit a číst z novýho...

**Comment by ondrejhlavacek** [comment]
Když jsem ten alter pustil podruhý, už byl svižnější, za 30 vteřin.

**Comment by Halama** [comment]
ono je blbý že to přidání nového sloupce by ničemu nepomohlo

**Comment by ondrejhlavacek** [comment]
jak to myslíš? kdyby se v dohledný době (týden?) odstranil, tak by to ničemu vadit nemuselo, ne?

**Comment by Halama** [comment]
no že v mysql není sloupcová db takže je celkem jedno jestli sloupec alteruješ nebo přidáváš novej. V 5.7 je online DDL ale je to takový trochu fake https://github.com/keboola/connection/issues/1620#issuecomment-436709141

**Comment by ondrejhlavacek** [comment]
Aha! Takže si nepomůžem, v tom případě bych to tam prostě poslal v dobu, kdy tam je statisticky nejmíň requestů?

```
SELECT CONCAT(DAYOFWEEK(`touch`), '-', HOUR(`touch`)), COUNT(*) FROM `SnowflakeAccount` WHERE YEAR(`touch`) >= 2018 GROUP BY 1 ORDER BY 2 DESC;
```

![image](https://user-images.githubusercontent.com/497675/53364241-ade91500-393e-11e9-9acf-61681d8c9878.png)

takže jakejkoliv den před půlnocí a máme šanci, že to sejme malý jednotky requestů a pokud vrátěj 500–504, tak na ně udělaj transformace retry, takže by to nemuselo vůbec nic shodit.

**Comment by Halama** [comment]
jo asi bych to udělal takhle.

**Comment by Halama** [comment]
btw. ty workspacy v té db teda zůstávají napořád a jsou označeny jako neaktivní? pamatuju si že tam byl nějaký garbage collection

**Comment by ondrejhlavacek** [comment]
jo, zůstávají, GC tam je, ale ten nemazal záznamy, jenom neaktivní workspacy + docker sandboxy. napadlo mě ho rozšířit i na záznamy, ale řekl bych, že se nám tím ztratí něco v telemetrii?

**Comment by Halama** [comment]
jo teď je dobrý že se to nemaže, na tom je postavený ted párování tech SNFLK queries

**Comment by ondrejhlavacek** [comment]
Jdu ještě vyzkoušet to live DDL, jak se to bude chovat při MODIFY

**Comment by ondrejhlavacek** [comment]
Tak ne, alterování sloupce tabulku zamkne, live DDL nepomůže.

**Comment by ondrejhlavacek** [comment]
`ALTER TABLE` v produkci proběhl za 4 vteřiny
